### ISSUE TITLE
执行weex main.we --qr  报一下错误请问是什么问题

### ISSUE THREAD

**Issue by liujianying** [hugojing/toolbox-weex#8]
delalu:src liujianying$ weex main.we --qr
ERR! ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to undefined
    at /usr/local/lib/node_modules/weex-toolkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:195:17
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/weex-toolkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:175:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/weex-toolkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:273:36)
    at OptionManager.init (/usr/local/lib/node_modules/weex-toolkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:414:10)
    at File.initOptions (/usr/local/lib/node_modules/weex-toolkit/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/usr/local/lib/node_modules/weex-toolkit/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/usr/local/lib/node_modules/weex-toolkit/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/usr/local/lib/node_modules/weex-toolkit/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/usr/local/lib/node_modules/weex-toolkit/node_modules/babel-loader/index.js:131:12) 
ERR! ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to undefined

**Comment by hugojing** [comment]
weex-toolkit 没装好吧。
